### PR TITLE
Fix print issue with reporter

### LINKED ISSUE #87: Fix last line of output sometimes getting eaten
See https://github.com/brioche-dev/brioche/issues/86#issuecomment-2226389904

### PR DESCRIPTION
**Pull request by jaudiger**
Resolve #87.

To be reviewed one commit at a time. The last commit could be removed from this PR, since it has no impact on resolving the issue #87. I just found a quick refactoring which led to suppressing a return statement.

Before the fix, reformatting multiple projects at once was printing:

```bash
[826µs] 0 / 0 jobs complete
[102.8ms] 0 / 0 jobs complete
All files of project '../brioche-packages/packages/biome' are formatted
```

After the fix, the command is now correctly printing its output:

```bash
All files of project '../brioche-packages/packages/go' are formatted
All files of project '../brioche-packages/packages/biome' are formatted
Error occurred while formatting project '../brioche-packages/packages/g': failed to canonicalize path ../brioche-packages/packages/g
```

### CODE REVIEW

File: crates/brioche/src/format.rs [hunk 1]
```diff
@@ -26,11 +26,17 @@ pub async fn format(args: FormatArgs) -> anyhow::Result<ExitCode> {
...
-                    err = err
-                );
+                reporter.emit(superconsole::Lines::from_multiline_string(
+                    &format!(
+                        "Error occurred while formatting project '{project_path}': {err}",
+                        project_path = project_path.display(),
+                        err = err
+                    ),
+                    superconsole::style::ContentStyle {
+                        foreground_color: Some(superconsole::style::Color::Red),
```
Comment (jaudiger) [inline crates/brioche/src/format.rs:36]: Should I leave it red ? I’ll be inconsistent with the other commands I think. Unless we try to make use of the reporter everywhere else.

**Review by kylewlacy — APPROVED** [review]
LGTM
